Scene Index table view fixes and tweaks
Whisparr/Whisparr pull request #166
Opened 2024-03-05 06:36 UTC by plz12345

#### Database Migration
NO

#### Description
* Fixed CSS for scene title so it doesn't flex behind the Studio column
* Made Studio name clickable to go to the studio detail sceen
* Fixed the toggle to monitor scenes while in edit mode.  This was looking for `movieId` as a property, and I think when this component was cloned, someone did a blanket find/replace for `movie` -> `scene`.  There may be a better fix, but it's working as desired now.

#### Screenshot (if UI related)
![image](https://github.com/Whisparr/Whisparr/assets/132735020/ba98fae5-4290-4e61-aaf7-112627e11533)
![image](https://github.com/Whisparr/Whisparr/assets/132735020/e489f3c2-85d0-49b5-b231-a7a80338dfc8)

#### Todos
- [ x] Tests
- [x ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ n/a] [Wiki Updates](https://wiki.servarr.com)

2024-03-11 13:43 UTC, Qstick requested changes, later dismissed

2024-03-11 13:43 UTC, Qstick commented on yarn.lock
> +  resolved "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001593.tgz"
Same note on this one. All else looks good

2024-03-11 21:22 UTC, plz12345 commented on yarn.lock
> +  resolved "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001593.tgz"
@Qstick I rolled back the 3 previous commits in my branch and re-pushed just one commit for all the changes noted in the PR, without the yarn lock file.

2024-03-17 01:22 UTC, Tom-Estes approved these changes

2024-03-17 01:23 UTC, merged