Fixed: Moved ability to monitor Studio away from Performer view
Whisparr/Whisparr pull request #190
Opened 2024-03-21 00:34 UTC by plz12345

#### Database Migration
NO

#### Description
It was too easy to conflate monitoring scenss vs. entire studios from the Performer view.  This change makes the mointor flag read-only, adds a tooltip to it indicating where to go, and links the Studio's name to go there.

#### Screenshot (if UI related)
<img width="371" alt="image" src="https://github.com/Whisparr/Whisparr/assets/132735020/95a7d2fc-d1e6-4c19-b0e4-4fb3d08bcdf4"> 
<img width="332" alt="image" src="https://github.com/Whisparr/Whisparr/assets/132735020/21dc8c1c-c8a5-4429-b799-c2fe6f269487">

#### Todos
- [x] Tests
- [x] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [x] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #180

2024-03-22 00:19 UTC, plz12345 commented
The failed test seems to be some HTTP timeout in the pipeline.  Maybe an admin can re-run it?

2024-03-24 23:35 UTC, Tom-Estes requested changes
Can you change:

```
if (!monitored) {
    return kinds.WARNING;
  }
```
to

```
if (!movieCount) {
    return kinds.WARNING;
  }
```

to keep it visually the same between pages. Without it, it'll look like there isn't any monitored and be yellow.

2024-03-25 01:08 UTC, plz12345 commented
> Can you change:
> 
> ```
> if (!monitored) {
>     return kinds.WARNING;
>   }
> ```
> 
> to
> 
> ```
> if (!movieCount) {
>     return kinds.WARNING;
>   }
> ```
> 
> to keep it visually the same between pages. Without it, it'll look like there isn't any monitored and be yellow.

Done

2024-03-25 01:47 UTC, Tom-Estes approved these changes

2024-03-25 01:47 UTC, merged

2024-03-27 20:44 UTC, sampulsar commented
@plz12345 

Can you fix this for the light theme as the link is not visible.

2024-03-27 23:32 UTC, plz12345 commented
> @plz12345
> 
> Can you fix this for the light theme as the link is not visible.

Should I do a new PR for that?

2024-03-28 03:33 UTC, sampulsar commented
yes, so it can be merged

2024-03-28 22:41 UTC, plz12345 commented
Should I just remove my CSS override?  I just didn't like the blue color default, personally.

2024-03-29 05:38 UTC, sampulsar commented
Change it to 'inherit' so it gets it from the class before the link as that was what is was before.

2024-03-29 22:06 UTC, plz12345 commented
> Change it to 'inherit' so it gets it from the class before the link as that was what is was before.

Fixed in #211